trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:

# Checkout
- checkout: self
  clean: true

# Install .NET SDK
- task: UseDotNet@2
  displayName: Install .NET 10 SDK
  inputs:
    packageType: sdk
    version: 10.x

# Restore
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: restore
    projects: '**/CrackJobs.csproj'

# Build
- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build
    projects: '**/CrackJobs.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

# Deploy to Azure VM
- task: SSH@0
  displayName: Deploy Docker Container
  inputs:
    sshEndpoint: 'AzureVM-SSH'
    runOptions: 'inline'
    readyTimeout: '20000'
    inline: |
      set -e

      echo "Moving to source folder..."
      cd /home/kkmail2027/git-source/API-code/CrackJobs

      echo "Pulling latest code..."
      git pull

      echo "Building Docker Image..."
      docker build -t crackjobs-api:latest .

      echo "Stopping old container..."
      docker stop crackjobs-api || true

      echo "Removing old container..."
      docker rm crackjobs-api || true

      echo "Starting new container..."
      docker run -d \
        --name crackjobs-api \
        --restart unless-stopped \
        -p 8081:8080 \
        crackjobs-api:latest

      echo "Waiting for application..."
      sleep 15

      echo "Health Check"
      curl http://localhost:8081/health

      echo "Deployment Successful"