# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo CI Pipeline started
  displayName: 'Run a one-line script'

  # Checkout source code
- checkout: self

# Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

#Diagnose
- script: |
    echo "Current directory:"
    pwd
    echo "Files:"
    ls -la
    echo "Searching for solution and project files..."
    find . -name "*.csproj"
    find . -name "*.sln"
    find . -name "*.slnx"
    find . -name "*.esproj"
  displayName: 'Debug Repository'

# Restore packages
- script: |
    dotnet restore
  displayName: 'Restore NuGet Packages'

# Build
- script: |
    dotnet build CrackJobs.csproj --configuration Release --no-restore
  displayName: 'Build Project'

# Run Tests (if any)
#- script: |
    #dotnet test --no-build --configuration $(buildConfiguration)
  #displayName: 'Run Tests'
  #continueOnError: true

# Publish
- script: |
    dotnet publish CrackJobs.csproj --configuration Release --no-build --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish API'

# Publish Artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'API'

- script: |
    echo All CI Tasks are  completed.
    echo See https://aka.ms/yaml
  displayName: 'CI Pipeline completed'

- task: SSH@0
  displayName: 'Test SSH Connection'
  inputs:
    sshEndpoint: 'AzureVM-SSH'
    runOptions: 'inline'
    inline: |
      echo "=========================="
      echo "SSH Connected Successfully"
      echo "=========================="

     # whoami
     # hostname
     # pwd
     # ls -la /home/kkmail2027

# Download the published artifact
- task: DownloadBuildArtifacts@1
  displayName: 'Download Build Artifact'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'API'
    downloadPath: '$(Pipeline.Workspace)'

- task: CopyFilesOverSSH@0
  displayName: 'Deploy API to Azure VM'
  inputs:
    sshEndpoint: 'AzureVM-SSH'
    sourceFolder: '$(Pipeline.Workspace)/API'
    contents: '**'
    targetFolder: '/home/kkmail2027/code/API'
    cleanTargetFolder: false
    overwrite: true

- task: SSH@0
  displayName: 'Restart API Service'
  inputs:
    sshEndpoint: 'AzureVM-SSH'
    runOptions: 'inline'
    inline: |
      echo "Restarting API..."
      sudo systemctl restart myapi

      echo "Checking service status..."
      sudo systemctl status myapi --no-pager

      echo "Deployment completed."

- task: SSH@0
  displayName: 'Verify Deployment'
  inputs:
    sshEndpoint: 'AzureVM-SSH'
    runOptions: 'inline'
    inline: |
      echo "Testing API..."
      curl http://localhost/api/masterdata/questions
