// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrackJobs.Domain;

public partial class Comment
{
    public long Id { get; set; }

    public string Comment1 { get; set; }

    public string UserId { get; set; }

    public long? ParrentCommentId { get; set; }

    public long? LikeCount { get; set; }

    public long? ReplyCount { get; set; }

    public bool? IsDeleted { get; set; }

    public long? QuestionId { get; set; }

    public DateTime? CreatedDate { get; set; }
}