// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrackJobs.Domain;

public partial class Questinon
{
    public long Qid { get; set; }

    public string Qname { get; set; }

    public string Qdesc { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<QuestionTechnologyMap> QuestionTechnologyMaps { get; set; } = new List<QuestionTechnologyMap>();
}