// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrackJobs.Domain;

public partial class QuestionCompanyMap
{
    public long Id { get; set; }

    public long Qid { get; set; }

    public int CompId { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}