// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace CrackJobs.Domain;

public partial class QuestionTechnologyMap
{
    public int Id { get; set; }

    public long Qid { get; set; }

    public int TechId { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public byte[] CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdateBy { get; set; }

    public virtual Questinon QidNavigation { get; set; }

    public virtual Technology Tech { get; set; }
}