// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrackJobs.Domain;

public partial class QuestionAnswerMap
{
    public long Id { get; set; }

    public long Qid { get; set; }

    public long Aid { get; set; }

    public bool IsActive { get; set; }

    public long RatingId { get; set; }

    public long CommentId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}