// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CrackJobs.Domain;
using Microsoft.EntityFrameworkCore;


namespace CrackJobs.Infrastructure.Data;

public partial class CrackJobContext : DbContext
{
    public CrackJobContext()
    {
    }

    public CrackJobContext(DbContextOptions<CrackJobContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Answer> Answers { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<JobRole> JobRoles { get; set; }

    public virtual DbSet<QuestionJobRoleMap> QuestionJobRoleMaps { get; set; }

    public virtual DbSet<Like> Likes { get; set; }

    public virtual DbSet<Company> Companies { get; set; }

    public virtual DbSet<Questinon> Questinons { get; set; }

    public virtual DbSet<QuestionAnswerMap> QuestionAnswerMaps { get; set; }

    public virtual DbSet<QuestionCompanyMap> QuestionCompanyMaps { get; set; }

    public virtual DbSet<QuestionTechnologyMap> QuestionTechnologyMaps { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Technology> Technologies { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=CrackJob;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Answer>(entity =>
        {
            entity.HasKey(e => e.Aid);

            entity.Property(e => e.Aid).HasColumnName("AID");
            entity.Property(e => e.Answer1)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("Answer");
            entity.Property(e => e.AnswerReference)
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Comment1)
                .IsRequired()
                .HasMaxLength(5000)
                .IsUnicode(false)
                .HasColumnName("Comment");
            entity.Property(e => e.ParrentCommentId).HasColumnName("ParrentCommentID");
            entity.Property(e => e.UserId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("UserID");
            entity.Property(e => e.QuestionId).HasColumnName("QuestionID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<JobRole>(entity =>
        {
            entity.HasKey(e => e.RoleId);

            entity.ToTable("JobRole");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.RoleDescription)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<QuestionJobRoleMap>(entity =>
        {
            entity.ToTable("QuestionJobRoleMap");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Qid).HasColumnName("QID");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.CreatedBy).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy).HasMaxLength(50).IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Like>(entity =>
        {
            entity.ToTable("Like");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("UserID");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TargetId).HasColumnName("TargetID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Company>(entity =>
        {
            entity.ToTable("Company");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CompanyDescription)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(2000)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Questinon>(entity =>
        {
            entity.HasKey(e => e.Qid);

            entity.Property(e => e.Qid).HasColumnName("QID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Qdesc)
                .HasMaxLength(2000)
                .IsUnicode(false)
                .HasColumnName("QDesc");
            entity.Property(e => e.Qname)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("QName");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<QuestionAnswerMap>(entity =>
        {
            entity.ToTable("QuestionAnswerMap");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Aid).HasColumnName("AID");
            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Qid).HasColumnName("QID");
            entity.Property(e => e.RatingId).HasColumnName("RatingID");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<QuestionCompanyMap>(entity =>
        {
            entity.ToTable("QuestionCompanyMap");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CompId).HasColumnName("CompID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Qid).HasColumnName("QID");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<QuestionTechnologyMap>(entity =>
        {
            entity.ToTable("QuestionTechnologyMap");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Qid).HasColumnName("QID");
            entity.Property(e => e.TechId).HasColumnName("TechID");
            entity.Property(e => e.UpdateBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.QidNavigation).WithMany(p => p.QuestionTechnologyMaps)
                .HasForeignKey(d => d.Qid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionTechnologyMap_QuestionTechnologyMap");

            entity.HasOne(d => d.Tech).WithMany(p => p.QuestionTechnologyMaps)
                .HasForeignKey(d => d.TechId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionTechnologyMap_Technology");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.Rid);

            entity.ToTable("Rating");

            entity.Property(e => e.Rid)
                .ValueGeneratedNever()
                .HasColumnName("RID");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Technology>(entity =>
        {
            entity.HasKey(e => e.TechId);

            entity.ToTable("Technology");

            entity.Property(e => e.TechId).HasColumnName("TechID");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.TechDescription)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.TechName)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}